# Generated by Django 4.1.7 on 2023-04-27 15:45

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntf_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('destination', models.CharField(choices=[('Email', 'Email'), ('SMS', 'Sms')], max_length=255, verbose_name='Destination')),
                ('type', models.CharField(choices=[('event', 'Some event'), ('personal', 'Unique letter'), ('new', 'New movie/TV series')], max_length=255, verbose_name='Notification type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('content', models.CharField(blank=True, max_length=255, verbose_name='Content (ex. movie_id)')),
                ('priority', models.CharField(choices=[('high', 'High'), ('low', 'Low')], default='high', max_length=255, verbose_name='Event priority')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sending time')),
                ('source', models.CharField(choices=[('Admin', 'Created by admin'), ('Auto', 'Generated automatically'), ('Service', 'Generated by any service')], default='Admin', max_length=255, verbose_name='Source')),
                ('status', models.CharField(choices=[('done', 'Done'), ('undone', 'Undone')], default='undone', max_length=255, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification"."notice',
            },
        ),
    ]
