# Generated by Django 4.1.7 on 2023-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content',
            field=models.CharField(blank=True, max_length=255, verbose_name='Content (ex. movie_id)'),
        ),
    ]
