version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: postgres_db
    volumes:
      -  $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=movies_db
    networks:
      - postgres-network


networks:
  postgres-network:
    external:
      name: movie-network
