version: '3.9'

services:
  admin_panel:
    container_name: admin_panel
    build:
      context: ../admin_panel
      dockerfile: Dockerfile
    command: python manage.py runserver
    env_file:
      - ../admin_panel/config/.env
    networks:
      - admin-network


networks:
  admin-network:
    external:
      name: movie-network
